---
output:
  github_document:
    html_preview: false
    toc: true
    toc_depth: 2
---

<!-- README.md is generated from README.Rmd. Please edit that file -->


```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
  # fig.path = "README-"
)
options(tibble.print_min = 5, tibble.print_max = 5)
```


### R-miscellany

A collection of useful R code bits I'm tired of looking up.

### Data reading and writing

### Data manipulation

Drop columns from data frame by name:
```{r eval=FALSE}
iris[!colnames(iris) %in% c("Sepal.Length","Sepal.Width")]
```


### Timestamps

### Plots

Four plots in one graph:
```{r eval=FALSE}
par(mfrow=c(2,2))
```

### Rmarkdown template

```{text eval=FALSE}
# ---
# title: "Document Title"
# output: 
#   html_document:
#     theme: cerulean
#     highlight: textmate
#     fig_width: 8
#     fig_height: 5
#     toc: true
# ---
# 
# ```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_knit$set(root.dir = "some/directory")
# ```

```

